const mongoose = require("mongoose");
const { ObjectID } = require("mongodb");
const Schema = mongoose.Schema;

const postSchema = new Schema(
  {
    //id is automatically generated by mongoDB atlas
    author: {
      type: String,
    },

    authorID:{
      type:String,
    },

    title: {
      type: String,
    },

    favoriteCount: {
      type: Number,
    },

    description: {
      type: String,
    },
    photo: {
      type: String,
    },
    musicLink: {
      type: String,
    },

    comments: [
      {
        //id is automatically generated by mongoDB atlas
        comment: String,
        username: String,
        date: Date,
      },
    ],
  },
  { timestamps: true }
);

const Post = mongoose.model("Post", postSchema);

module.exports = Post;
