const mongoose = require("mongoose");
const { ObjectID } = require("mongodb");
const Schema = mongoose.Schema;

const userSchema = new Schema(
  {
    //id is automatically generated by mongoDB atlas

    profileImage: {
      type: String,
    },

    coverImage: {
      type: String,
    },

    birthday: {
      type: Date,
    },

    city: {
      type: String,
    },

    gender: {
      type: String,
    },

    firstName: {
      type: String,
      required: true,
    },

    lastName: {
      type: String,
      required: true,
    },

    email: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
    },

    username: {
      type: String,
      required: true,
    },

    password: {
      type: String,
      required: true,
      minlength: 6,
    },

    posts: [
      {
        _id: ObjectID,
        title: String,
        content: String,
        dateCreated: Date,
      },
    ],

    playlists: [
      {
        postID: String,
        author: String,
        photo: String,
        music: String,
        title: String,
        description: String,
      },
    ],

    favoritePlaylists: [
      {
        _id: ObjectID,
        playlistName: String,
        dateCreated: Date,
      },
    ],

    followed: [
      {
        _id: ObjectID,
        username: String,
      },
    ],

    following: [
      {
        _id: ObjectID,
        username: String,
      },
    ],
  },
  { timestamps: true }
);

const User = mongoose.model("User", userSchema);

module.exports = User;
